site_name: FRDR Documentation
site_url: http://127.0.0.1:8000/
plausible_domain: test.frdr.ca
theme:
    name: mkdocs
    custom_dir: 'frdr_theme'
nav:
    - English:
        - "Preparing Your Data": en/preparing_your_data.md
        - "Before Depositing": en/before_depositing.md
        - "Describing Your Data": en/describing_your_data.md
        - "Depositing Data": en/depositing_data.md
        - "After Depositing": en/after_depositing.md
        - "Searching for Datasets": en/searching.md
        - "Advanced": en/advanced.md
        - "FAQ": en/faq.md
        - "Change Log": en/change_log.md
        - "FAIR Principles": en/fair_principles.md
        - "Style Guide": en/style_guide.md
    - French:
        - "Préparation de vos données": fr/préparation_de_vos_données.md
        - "Avant de déposer": fr/avant_de_déposer.md
        - "Description de vos données": fr/description_de_vos_données.md
        - "Déposer les données": fr/déposer_les_données.md
        - "Après le dépôt": fr/après_le_dépôt.md
        - "Recherche de jeux de données": fr/recherche.md
        - "Avancée": fr/avancee.md
        - "FAQ": fr/faq.md
        - "Principes FAIR": fr/principes_fair.md
        - "Guide de style": fr/guide_de_style.md

extra_css:
    - css/docs-theme.css
extra:
    repo_url: https://www.frdr-dfdr.ca/repo/
    prefix: "/"
    default_page_en: en/documentation/
    default_page_fr: fr/documentation/
    language_map:
        en:
            "About": fr/à_propos/
            "Searching for Datasets": fr/recherche/
            "Preparing Your Data": fr/préparation_de_vos_données/
            "Before Depositing": fr/avant_de_déposer/
            "Describing Your Data": fr/description_de_vos_données/
            "Depositing Data": fr/déposer_les_données/
            "After Depositing": fr/après_le_dépôt/
            "FAQ": fr/faq/
            "FAIR Principles": fr/principes_fair/
            "Style Guide": fr/guide_de_style/
            "Advanced": fr/avancee/
        fr:
            "À propos": en/about/
            "Recherche de jeux de données": en/searching/
            "Préparation de vos données": en/preparing_your_data/
            "Avant de déposer": en/before_depositing/
            "Description de vos données": en/describing_your_data/
            "Déposer les données": en/depositing_data/
            "Après le dépôt": en/after_depositing/
            "FAQ": en/faq/
            "Principes FAIR": en/fair_principles/
            "Guide de style": en/style_guide/
            "Avancée": en/advanced/
