site_name: FRDR Documentation
site_url: http://127.0.0.1:8000/
theme:
    name: mkdocs
    custom_dir: 'frdr_theme'
nav:
    - English:
        - "About": en/about.md
        - "Searching for Datasets": en/searching.md
        - "Preparing Your Data": en/preparing_your_data.md
        - "Before Depositing": en/before_depositing.md
        - "Describing Your Data": en/describing_your_data.md
        - "Depositing Data": en/depositing_data.md
        - "After Depositing": en/after_depositing.md
        - "Terms of Use": en/terms_of_use.md
        - "Privacy Policy": en/privacy_policy.md
        - "Advanced": en/advanced.md
        - "FAQ": en/faq.md
        - "Change Log": en/change_log.md
        - "FAIR Principles": en/fair_principles.md
        - "Style Guide": en/style_guide.md
        - "Contact Us": en/contact_support.md
    - French:
        - "À propos": fr/a_propos.md
        - "Recherche de jeux de données": fr/recherche.md
        - "Préparation de vos données": fr/préparation_de_vos_données.md
        - "Avant de déposer": fr/avant_de_déposer.md
        - "Déposer les données": fr/déposer_les_données.md
        - "Après le dépôt": fr/après_le_dépôt.md
        - "Conditions d'utilisation": fr/conditions_d'utilisation.md
        - "Politique de confidentialité": fr/politique_de_confidentialité.md
        - "Avancée": fr/avancee.md
        - "FAQ": fr/faq.md
        - "Principes FAIR": fr/principes_fair.md
        - "Guide de style": fr/guide_de_style.md
        - "Contactez nous": fr/contactez_nous.md

extra_css:
    - css/docs-theme.css
extra:
    repo_url: https://www.frdr-dfdr.ca/repo/
    prefix: "/"
    default_page_en: en/about/
    default_page_fr: fr/a_propos/
    language_map:
        en:
            "About": fr/a_propos/
            "Searching for Datasets": fr/recherche/
            "Preparing Your Data": fr/préparation_de_vos_données/
            "Before Depositing": fr/avant_de_déposer/
            "Depositing Data": fr/déposer_les_données/
            "After Depositing": fr/après_le_dépôt/
            "Terms of Use": fr/conditions_d'utilisation/
            "Privacy Policy": fr/politique_de_confidentialité/
            "FAQ": fr/faq/
            "FAIR Principles": fr/principes_fair/
            "Style Guide": fr/guide_de_style/
            "Contact Us": fr/contactez_nous/
            "Advanced": fr/avancee/
        fr:
            "À propos": en/about/
            "Recherche de jeux de données": en/searching/
            "Préparation de vos données": en/preparing_your_data/
            "Avant de déposer": en/before_depositing/
            "Déposer les données": en/depositing_data/
            "Après le dépôt": en/after_depositing/
            "Conditions d'utilisation": en/terms_of_use/
            "Politique de confidentialité": en/privacy_policy/
            "FAQ": en/faq/
            "Principes FAIR": en/fair_principles/
            "Guide de style": en/style_guide/
            "Contactez nous": en/contact_support/
            "Avancée": en/advanced/
